# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0041d19cd8ae15d4211da74d07203f85cabd0808407ab48da2ff06c00bba192b39a426cab3ed7339c6c29f433a709d154ddad67a1fd562cea7bb1ec1c258c8a

test:
  secret_key_base: 76f1608a6aaa2ea5b538b52f0b19ef2df9ccf039f576653c3f82cbe8048ec71c8479fc5344a0bd04af24f4656cc72a81bb8ba2e6590b77e17a8f2faec622b253

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
